export const modules = [
    {
        "type":"职业态度",
        "scoreRateDistribution":[
            "95.83",
            "20.73",
            "16.70",
            "11.46",
            "7.68",
            "10.51",
            "6.01",
            "4.73",
            "2.60",
            "2.41",
            "2.91",
            "4.79",
            "1.50",
            "3.81"
        ],
        "distribution":{
            "distribution0":[
                {
                    "name":"优秀",
                    "value":1499,
                    "proportion":99.81
                },
                {
                    "name":"良好",
                    "value":22,
                    "proportion":95
                },
                {
                    "name":"及格",
                    "value":860,
                    "proportion":91.54
                },
                {
                    "name":"不及格",
                    "value":169,
                    "proportion":82.51
                }
            ],
            "distribution1":[
                {
                    "name":"优秀",
                    "value":344,
                    "proportion":99.8
                },
                {
                    "name":"良好",
                    "value":4,
                    "proportion":95
                },
                {
                    "name":"及格",
                    "value":181,
                    "proportion":91.59
                },
                {
                    "name":"不及格",
                    "value":19,
                    "proportion":83.33
                }
            ],
            "distribution2":[
                {
                    "name":"优秀",
                    "value":350,
                    "proportion":99.84
                },
                {
                    "name":"良好",
                    "value":6,
                    "proportion":95
                },
                {
                    "name":"及格",
                    "value":69,
                    "proportion":91.59
                },
                {
                    "name":"不及格",
                    "value":9,
                    "proportion":84.07
                }
            ],
            "distribution3":[
                {
                    "name":"优秀",
                    "value":240,
                    "proportion":99.85
                },
                {
                    "name":"良好",
                    "value":5,
                    "proportion":95
                },
                {
                    "name":"及格",
                    "value":43,
                    "proportion":91.67
                },
                {
                    "name":"不及格",
                    "value":10,
                    "proportion":83.5
                }
            ],
            "distribution4":[
                {
                    "name":"优秀",
                    "value":68,
                    "proportion":99.9
                },
                {
                    "name":"及格",
                    "value":117,
                    "proportion":91.55
                },
                {
                    "name":"不及格",
                    "value":25,
                    "proportion":82.93
                }
            ],
            "distribution5":[
                {
                    "name":"优秀",
                    "value":101,
                    "proportion":99.93
                },
                {
                    "name":"良好",
                    "value":1,
                    "proportion":95
                },
                {
                    "name":"及格",
                    "value":150,
                    "proportion":91.6
                },
                {
                    "name":"不及格",
                    "value":35,
                    "proportion":81.9
                }
            ],
            "distribution6":[
                {
                    "name":"优秀",
                    "value":95,
                    "proportion":99.6
                },
                {
                    "name":"良好",
                    "value":1,
                    "proportion":95
                },
                {
                    "name":"及格",
                    "value":53,
                    "proportion":91.42
                },
                {
                    "name":"不及格",
                    "value":11,
                    "proportion":83.18
                }
            ],
            "distribution7":[
                {
                    "name":"优秀",
                    "value":100,
                    "proportion":99.88
                },
                {
                    "name":"及格",
                    "value":18,
                    "proportion":91.3
                },
                {
                    "name":"不及格",
                    "value":5,
                    "proportion":85.33
                }
            ],
            "distribution8":[
                {
                    "name":"优秀",
                    "value":48,
                    "proportion":99.58
                },
                {
                    "name":"及格",
                    "value":16,
                    "proportion":91.77
                },
                {
                    "name":"不及格",
                    "value":5,
                    "proportion":77.67
                }
            ],
            "distribution9":[
                {
                    "name":"优秀",
                    "value":45,
                    "proportion":99.63
                },
                {
                    "name":"良好",
                    "value":3,
                    "proportion":95
                },
                {
                    "name":"及格",
                    "value":10,
                    "proportion":91
                },
                {
                    "name":"不及格",
                    "value":6,
                    "proportion":78.33
                }
            ],
            "distribution10":[
                {
                    "name":"优秀",
                    "value":40,
                    "proportion":99.92
                },
                {
                    "name":"及格",
                    "value":32,
                    "proportion":91.35
                },
                {
                    "name":"不及格",
                    "value":6,
                    "proportion":83.89
                }
            ],
            "distribution11":[
                {
                    "name":"优秀",
                    "value":2,
                    "proportion":99.17
                },
                {
                    "name":"及格",
                    "value":112,
                    "proportion":91.55
                },
                {
                    "name":"不及格",
                    "value":21,
                    "proportion":83.73
                }
            ],
            "distribution12":[
                {
                    "name":"优秀",
                    "value":9,
                    "proportion":99.81
                },
                {
                    "name":"良好",
                    "value":1,
                    "proportion":95
                },
                {
                    "name":"及格",
                    "value":25,
                    "proportion":91.47
                },
                {
                    "name":"不及格",
                    "value":7,
                    "proportion":76.19
                }
            ],
            "distribution13":[
                {
                    "name":"优秀",
                    "value":57,
                    "proportion":99.65
                },
                {
                    "name":"良好",
                    "value":1,
                    "proportion":95
                },
                {
                    "name":"及格",
                    "value":34,
                    "proportion":91.32
                },
                {
                    "name":"不及格",
                    "value":10,
                    "proportion":83.5
                }
            ]
        },
        "distributionTable":[
            {
                "name":"幼儿园教师",
                "excellent":"62.77(344人)",
                "good":"0.73(4人)",
                "pass":"33.03(181人)",
                "fail":"3.47(19人)"
            },
            {
                "name":"义务教育语文教师",
                "excellent":"80.65(350人)",
                "good":"1.38(6人)",
                "pass":"15.90(69人)",
                "fail":"2.07(9人)"
            },
            {
                "name":"义务教育数学教师",
                "excellent":"80.54(240人)",
                "good":"1.68(5人)",
                "pass":"14.43(43人)",
                "fail":"3.36(10人)"
            },
            {
                "name":"义务教育英语教师",
                "excellent":"32.38(68人)",
                "good":"0(0人)",
                "pass":"55.71(117人)",
                "fail":"11.90(25人)"
            },
            {
                "name":"义务教育艺体科教师",
                "excellent":"35.19(101人)",
                "good":"0.35(1人)",
                "pass":"52.26(150人)",
                "fail":"12.20(35人)"
            },
            {
                "name":"义务教育社会科教师",
                "excellent":"59.38(95人)",
                "good":"0.63(1人)",
                "pass":"33.13(53人)",
                "fail":"6.88(11人)"
            },
            {
                "name":"义务教育理工科教师",
                "excellent":"81.30(100人)",
                "good":"0(0人)",
                "pass":"14.63(18人)",
                "fail":"4.07(5人)"
            },
            {
                "name":"高中教育（含职业院校）语文教师",
                "excellent":"69.57(48人)",
                "good":"0(0人)",
                "pass":"23.19(16人)",
                "fail":"7.25(5人)"
            },
            {
                "name":"高中学段（含职校）数学教师",
                "excellent":"70.31(45人)",
                "good":"4.69(3人)",
                "pass":"15.63(10人)",
                "fail":"9.38(6人)"
            },
            {
                "name":"高中学段（含职校） 英语教师",
                "excellent":"51.28(40人)",
                "good":"0(0人)",
                "pass":"41.03(32人)",
                "fail":"7.69(6人)"
            },
            {
                "name":"高中学段（含职校）理工科教师",
                "excellent":"1.48(2人)",
                "good":"0(0人)",
                "pass":"82.96(112人)",
                "fail":"15.56(21人)"
            },
            {
                "name":"高中学段（含职校）艺体科教师",
                "excellent":"21.43(9人)",
                "good":"2.38(1人)",
                "pass":"59.52(25人)",
                "fail":"16.67(7人)"
            },
            {
                "name":"高中学段（含职校）社会科教师",
                "excellent":"55.88(57人)",
                "good":"0.98(1人)",
                "pass":"33.33(34人)",
                "fail":"9.80(10人)"
            }
        ],
        "average":{
            "attitudeAver":[
                {
                    "name":"幼儿园教师",
                    "value":12
                },
                {
                    "name":"义务教育语文教师",
                    "value":10
                },
                {
                    "name":"义务教育数学教师",
                    "value":6
                },
                {
                    "name":"义务教育英语教师",
                    "value":4
                },
                {
                    "name":"义务教育艺体科教师",
                    "value":6
                },
                {
                    "name":"义务教育社会科教师",
                    "value":3
                },
                {
                    "name":"义务教育理工科教师",
                    "value":2
                },
                {
                    "name":"高中教育（含职业院校）语文教师",
                    "value":1
                },
                {
                    "name":"高中学段（含职校）数学教师",
                    "value":1
                },
                {
                    "name":"高中学段（含职校） 英语教师",
                    "value":1
                },
                {
                    "name":"高中学段（含职校）理工科教师",
                    "value":2
                },
                {
                    "name":"高中学段（含职校）艺体科教师",
                    "value":0
                },
                {
                    "name":"高中学段（含职校）社会科教师",
                    "value":2
                }
            ],
            "attitudeAverScene":[
                {
                    "name":"幼儿园教师",
                    "value":12
                },
                {
                    "name":"义务教育语文教师",
                    "value":10
                },
                {
                    "name":"义务教育数学教师",
                    "value":6
                },
                {
                    "name":"义务教育英语教师",
                    "value":4
                },
                {
                    "name":"义务教育艺体科教师",
                    "value":6
                },
                {
                    "name":"义务教育社会科教师",
                    "value":3
                },
                {
                    "name":"义务教育理工科教师",
                    "value":2
                },
                {
                    "name":"高中教育（含职业院校）语文教师",
                    "value":1
                },
                {
                    "name":"高中学段（含职校）数学教师",
                    "value":1
                },
                {
                    "name":"高中学段（含职校） 英语教师",
                    "value":1
                },
                {
                    "name":"高中学段（含职校）理工科教师",
                    "value":2
                },
                {
                    "name":"高中学段（含职校）艺体科教师",
                    "value":0
                },
                {
                    "name":"高中学段（含职校）社会科教师",
                    "value":2
                }
            ],
            "attitudeAverSelf":[
                {
                    "name":"幼儿园教师",
                    "value":12
                },
                {
                    "name":"义务教育语文教师",
                    "value":10
                },
                {
                    "name":"义务教育数学教师",
                    "value":6
                },
                {
                    "name":"义务教育英语教师",
                    "value":4
                },
                {
                    "name":"义务教育艺体科教师",
                    "value":6
                },
                {
                    "name":"义务教育社会科教师",
                    "value":3
                },
                {
                    "name":"义务教育理工科教师",
                    "value":2
                },
                {
                    "name":"高中教育（含职业院校）语文教师",
                    "value":1
                },
                {
                    "name":"高中学段（含职校）数学教师",
                    "value":1
                },
                {
                    "name":"高中学段（含职校） 英语教师",
                    "value":1
                },
                {
                    "name":"高中学段（含职校）理工科教师",
                    "value":2
                },
                {
                    "name":"高中学段（含职校）艺体科教师",
                    "value":0
                },
                {
                    "name":"高中学段（含职校）社会科教师",
                    "value":2
                }
            ]
        },
        "minMaxAndMidScene":[
            [
                22,
                30,
                30
            ],
            [
                22,
                30,
                30
            ],
            [
                21,
                30,
                30
            ],
            [
                6,
                30,
                30
            ],
            [
                22,
                30,
                30
            ],
            [
                24,
                30,
                30
            ],
            [
                23,
                30,
                30
            ],
            [
                12,
                30,
                30
            ],
            [
                18,
                30,
                30
            ],
            [
                24,
                30,
                30
            ],
            [
                22,
                30,
                30
            ],
            [
                6,
                30,
                30
            ],
            [
                23,
                30,
                30
            ]
        ],
        "minMaxAndMidSelf":[
            [
                30,
                30,
                30
            ],
            [
                22,
                30,
                30
            ],
            [
                30,
                30,
                30
            ],
            [
                30,
                25,
                30
            ],
            [
                24,
                25,
                30
            ],
            [
                29,
                30,
                30
            ],
            [
                24,
                30,
                30
            ],
            [
                24,
                30,
                30
            ],
            [
                29,
                30,
                30
            ],
            [
                30,
                30,
                30
            ],
            [
                24,
                25,
                30
            ],
            [
                6,
                25,
                30
            ],
            [
                27,
                30,
                30
            ]
        ],
        "standardScene":[
            {
                "name":"幼儿园教师",
                "value":1.16
            },
            {
                "name":"义务教育语文教师",
                "value":1.24
            },
            {
                "name":"义务教育数学教师",
                "value":3.79
            },
            {
                "name":"义务教育英语教师",
                "value":1.81
            },
            {
                "name":"义务教育艺体科教师",
                "value":1.2
            },
            {
                "name":"义务教育社会科教师",
                "value":1.47
            },
            {
                "name":"义务教育理工科教师",
                "value":1.77
            },
            {
                "name":"高中教育（含职业院校）语文教师",
                "value":5.51
            },
            {
                "name":"高中学段（含职校）数学教师",
                "value":2.41
            },
            {
                "name":"高中学段（含职校） 英语教师",
                "value":1.47
            },
            {
                "name":"高中学段（含职校）理工科教师",
                "value":1.78
            },
            {
                "name":"高中学段（含职校）艺体科教师",
                "value":4.23
            },
            {
                "name":"高中学段（含职校）社会科教师",
                "value":2.17
            }
        ],
        "standardSelf":[
            {
                "name":"幼儿园教师",
                "value":3.15
            },
            {
                "name":"义务教育语文教师",
                "value":1.94
            },
            {
                "name":"义务教育数学教师",
                "value":2.01
            },
            {
                "name":"义务教育英语教师",
                "value":3.26
            },
            {
                "name":"义务教育艺体科教师",
                "value":3.57
            },
            {
                "name":"义务教育社会科教师",
                "value":3.52
            },
            {
                "name":"义务教育理工科教师",
                "value":1.69
            },
            {
                "name":"高中教育（含职业院校）语文教师",
                "value":2.43
            },
            {
                "name":"高中学段（含职校）数学教师",
                "value":3.15
            },
            {
                "name":"高中学段（含职校） 英语教师",
                "value":3.78
            },
            {
                "name":"高中学段（含职校）理工科教师",
                "value":1.06
            },
            {
                "name":"高中学段（含职校）艺体科教师",
                "value":3.58
            },
            {
                "name":"高中学段（含职校）社会科教师",
                "value":3.41
            }
        ]
    },
    {
        "type":"教学实践",
        "scoreRateDistribution":[
            "90.88",
            "20.53",
            "15.44",
            "10.51",
            "7.55",
            "10.50",
            "5.38",
            "4.12",
            "2.37",
            "2.31",
            "2.77",
            "4.69",
            "1.40",
            "3.31"
        ],
        "distribution":{
            "distribution0":[
                {
                    "name":"优秀",
                    "value":515,
                    "proportion":99.57
                },
                {
                    "name":"良好",
                    "value":458,
                    "proportion":95.72
                },
                {
                    "name":"及格",
                    "value":623,
                    "proportion":91.8
                },
                {
                    "name":"不及格",
                    "value":954,
                    "proportion":83.27
                }
            ],
            "distribution1":[
                {
                    "name":"优秀",
                    "value":270,
                    "proportion":99.57
                },
                {
                    "name":"良好",
                    "value":91,
                    "proportion":95.63
                },
                {
                    "name":"及格",
                    "value":128,
                    "proportion":92.02
                },
                {
                    "name":"不及格",
                    "value":59,
                    "proportion":84.63
                }
            ],
            "distribution2":[
                {
                    "name":"优秀",
                    "value":63,
                    "proportion":99.51
                },
                {
                    "name":"良好",
                    "value":95,
                    "proportion":95.76
                },
                {
                    "name":"及格",
                    "value":113,
                    "proportion":91.69
                },
                {
                    "name":"不及格",
                    "value":163,
                    "proportion":83.7
                }
            ],
            "distribution3":[
                {
                    "name":"优秀",
                    "value":24,
                    "proportion":99.34
                },
                {
                    "name":"良好",
                    "value":65,
                    "proportion":95.71
                },
                {
                    "name":"及格",
                    "value":81,
                    "proportion":91.72
                },
                {
                    "name":"不及格",
                    "value":128,
                    "proportion":84.09
                }
            ],
            "distribution4":[
                {
                    "name":"优秀",
                    "value":38,
                    "proportion":99.58
                },
                {
                    "name":"良好",
                    "value":46,
                    "proportion":95.74
                },
                {
                    "name":"及格",
                    "value":55,
                    "proportion":91.92
                },
                {
                    "name":"不及格",
                    "value":71,
                    "proportion":84.79
                }
            ],
            "distribution5":[
                {
                    "name":"优秀",
                    "value":80,
                    "proportion":99.63
                },
                {
                    "name":"良好",
                    "value":70,
                    "proportion":95.75
                },
                {
                    "name":"及格",
                    "value":71,
                    "proportion":91.92
                },
                {
                    "name":"不及格",
                    "value":66,
                    "proportion":84.58
                }
            ],
            "distribution6":[
                {
                    "name":"优秀",
                    "value":4,
                    "proportion":99.17
                },
                {
                    "name":"良好",
                    "value":12,
                    "proportion":95.69
                },
                {
                    "name":"及格",
                    "value":28,
                    "proportion":91.88
                },
                {
                    "name":"不及格",
                    "value":116,
                    "proportion":82.74
                }
            ],
            "distribution7":[
                {
                    "name":"良好",
                    "value":10,
                    "proportion":95.75
                },
                {
                    "name":"及格",
                    "value":31,
                    "proportion":91.53
                },
                {
                    "name":"不及格",
                    "value":82,
                    "proportion":81.95
                }
            ],
            "distribution8":[
                {
                    "name":"优秀",
                    "value":3,
                    "proportion":99.17
                },
                {
                    "name":"良好",
                    "value":8,
                    "proportion":95.83
                },
                {
                    "name":"及格",
                    "value":22,
                    "proportion":91.48
                },
                {
                    "name":"不及格",
                    "value":36,
                    "proportion":82.41
                }
            ],
            "distribution9":[
                {
                    "name":"优秀",
                    "value":16,
                    "proportion":99.79
                },
                {
                    "name":"良好",
                    "value":14,
                    "proportion":95.71
                },
                {
                    "name":"及格",
                    "value":13,
                    "proportion":91.73
                },
                {
                    "name":"不及格",
                    "value":21,
                    "proportion":83.85
                }
            ],
            "distribution10":[
                {
                    "name":"优秀",
                    "value":10,
                    "proportion":99.83
                },
                {
                    "name":"良好",
                    "value":22,
                    "proportion":95.8
                },
                {
                    "name":"及格",
                    "value":16,
                    "proportion":91.35
                },
                {
                    "name":"不及格",
                    "value":30,
                    "proportion":83.19
                }
            ],
            "distribution11":[
                {
                    "name":"优秀",
                    "value":7,
                    "proportion":100
                },
                {
                    "name":"良好",
                    "value":18,
                    "proportion":95.56
                },
                {
                    "name":"及格",
                    "value":42,
                    "proportion":91.79
                },
                {
                    "name":"不及格",
                    "value":68,
                    "proportion":83.43
                }
            ],
            "distribution12":[
                {
                    "name":"良好",
                    "value":3,
                    "proportion":95.83
                },
                {
                    "name":"及格",
                    "value":8,
                    "proportion":91.98
                },
                {
                    "name":"不及格",
                    "value":31,
                    "proportion":81.94
                }
            ],
            "distribution13":[
                {
                    "name":"良好",
                    "value":4,
                    "proportion":95.63
                },
                {
                    "name":"及格",
                    "value":15,
                    "proportion":91.44
                },
                {
                    "name":"不及格",
                    "value":83,
                    "proportion":80.47
                }
            ]
        },
        "distributionTable":[
            {
                "name":"幼儿园教师",
                "excellent":"49.27(270人)",
                "good":"16.61(91人)",
                "pass":"23.36(128人)",
                "fail":"10.77(59人)"
            },
            {
                "name":"义务教育语文教师",
                "excellent":"14.52(63人)",
                "good":"21.89(95人)",
                "pass":"26.04(113人)",
                "fail":"37.56(163人)"
            },
            {
                "name":"义务教育数学教师",
                "excellent":"8.05(24人)",
                "good":"21.81(65人)",
                "pass":"27.18(81人)",
                "fail":"42.95(128人)"
            },
            {
                "name":"义务教育英语教师",
                "excellent":"18.10(38人)",
                "good":"21.90(46人)",
                "pass":"26.19(55人)",
                "fail":"33.81(71人)"
            },
            {
                "name":"义务教育艺体科教师",
                "excellent":"27.87(80人)",
                "good":"24.39(70人)",
                "pass":"24.74(71人)",
                "fail":"23.00(66人)"
            },
            {
                "name":"义务教育社会科教师",
                "excellent":"2.50(4人)",
                "good":"7.50(12人)",
                "pass":"17.50(28人)",
                "fail":"72.50(116人)"
            },
            {
                "name":"义务教育理工科教师",
                "excellent":"0(0人)",
                "good":"8.13(10人)",
                "pass":"25.20(31人)",
                "fail":"66.67(82人)"
            },
            {
                "name":"高中教育（含职业院校）语文教师",
                "excellent":"4.35(3人)",
                "good":"11.59(8人)",
                "pass":"31.88(22人)",
                "fail":"52.17(36人)"
            },
            {
                "name":"高中学段（含职校）数学教师",
                "excellent":"25.00(16人)",
                "good":"21.88(14人)",
                "pass":"20.31(13人)",
                "fail":"32.81(21人)"
            },
            {
                "name":"高中学段（含职校） 英语教师",
                "excellent":"12.82(10人)",
                "good":"28.21(22人)",
                "pass":"20.51(16人)",
                "fail":"38.46(30人)"
            },
            {
                "name":"高中学段（含职校）理工科教师",
                "excellent":"5.19(7人)",
                "good":"13.33(18人)",
                "pass":"31.11(42人)",
                "fail":"50.37(68人)"
            },
            {
                "name":"高中学段（含职校）艺体科教师",
                "excellent":"0(0人)",
                "good":"7.14(3人)",
                "pass":"19.05(8人)",
                "fail":"73.81(31人)"
            },
            {
                "name":"高中学段（含职校）社会科教师",
                "excellent":"0(0人)",
                "good":"3.92(4人)",
                "pass":"14.71(15人)",
                "fail":"81.37(83人)"
            }
        ],
        "average":{
            "attitudeAver":[
                {
                    "name":"幼儿园教师",
                    "value":24
                },
                {
                    "name":"义务教育语文教师",
                    "value":18
                },
                {
                    "name":"义务教育数学教师",
                    "value":12
                },
                {
                    "name":"义务教育英语教师",
                    "value":9
                },
                {
                    "name":"义务教育艺体科教师",
                    "value":12
                },
                {
                    "name":"义务教育社会科教师",
                    "value":6
                },
                {
                    "name":"义务教育理工科教师",
                    "value":4
                },
                {
                    "name":"高中教育（含职业院校）语文教师",
                    "value":2
                },
                {
                    "name":"高中学段（含职校）数学教师",
                    "value":2
                },
                {
                    "name":"高中学段（含职校） 英语教师",
                    "value":3
                },
                {
                    "name":"高中学段（含职校）理工科教师",
                    "value":5
                },
                {
                    "name":"高中学段（含职校）艺体科教师",
                    "value":1
                },
                {
                    "name":"高中学段（含职校）社会科教师",
                    "value":3
                }
            ],
            "attitudeAverScene":[
                {
                    "name":"幼儿园教师",
                    "value":24
                },
                {
                    "name":"义务教育语文教师",
                    "value":18
                },
                {
                    "name":"义务教育数学教师",
                    "value":12
                },
                {
                    "name":"义务教育英语教师",
                    "value":9
                },
                {
                    "name":"义务教育艺体科教师",
                    "value":12
                },
                {
                    "name":"义务教育社会科教师",
                    "value":6
                },
                {
                    "name":"义务教育理工科教师",
                    "value":4
                },
                {
                    "name":"高中教育（含职业院校）语文教师",
                    "value":2
                },
                {
                    "name":"高中学段（含职校）数学教师",
                    "value":2
                },
                {
                    "name":"高中学段（含职校） 英语教师",
                    "value":3
                },
                {
                    "name":"高中学段（含职校）理工科教师",
                    "value":5
                },
                {
                    "name":"高中学段（含职校）艺体科教师",
                    "value":1
                },
                {
                    "name":"高中学段（含职校）社会科教师",
                    "value":3
                }
            ],
            "attitudeAverSelf":[
                {
                    "name":"幼儿园教师",
                    "value":24
                },
                {
                    "name":"义务教育语文教师",
                    "value":18
                },
                {
                    "name":"义务教育数学教师",
                    "value":12
                },
                {
                    "name":"义务教育英语教师",
                    "value":9
                },
                {
                    "name":"义务教育艺体科教师",
                    "value":12
                },
                {
                    "name":"义务教育社会科教师",
                    "value":6
                },
                {
                    "name":"义务教育理工科教师",
                    "value":4
                },
                {
                    "name":"高中教育（含职业院校）语文教师",
                    "value":2
                },
                {
                    "name":"高中学段（含职校）数学教师",
                    "value":2
                },
                {
                    "name":"高中学段（含职校） 英语教师",
                    "value":3
                },
                {
                    "name":"高中学段（含职校）理工科教师",
                    "value":5
                },
                {
                    "name":"高中学段（含职校）艺体科教师",
                    "value":1
                },
                {
                    "name":"高中学段（含职校）社会科教师",
                    "value":3
                }
            ]
        },
        "minMaxAndMidScene":[
            [
                30,
                60,
                30
            ],
            [
                30,
                59,
                30
            ],
            [
                21,
                58,
                30
            ],
            [
                29,
                60,
                30
            ],
            [
                27,
                60,
                30
            ],
            [
                30,
                58,
                30
            ],
            [
                30,
                59,
                30
            ],
            [
                24,
                56,
                30
            ],
            [
                18,
                58,
                30
            ],
            [
                29,
                60,
                30
            ],
            [
                27,
                59,
                30
            ],
            [
                30,
                60,
                30
            ],
            [
                30,
                59,
                30
            ]
        ],
        "minMaxAndMidSelf":[
            [
                30,
                60,
                30
            ],
            [
                30,
                55,
                30
            ],
            [
                30,
                55,
                30
            ],
            [
                30,
                55,
                30
            ],
            [
                30,
                55,
                30
            ],
            [
                26,
                50,
                30
            ],
            [
                30,
                45,
                30
            ],
            [
                24,
                50,
                30
            ],
            [
                24,
                55,
                30
            ],
            [
                29,
                55,
                30
            ],
            [
                24,
                50,
                30
            ],
            [
                24,
                45,
                30
            ],
            [
                30,
                45,
                30
            ]
        ],
        "standardScene":[
            {
                "name":"幼儿园教师",
                "value":9.81
            },
            {
                "name":"义务教育语文教师",
                "value":6.42
            },
            {
                "name":"义务教育数学教师",
                "value":5.15
            },
            {
                "name":"义务教育英语教师",
                "value":9.01
            },
            {
                "name":"义务教育艺体科教师",
                "value":5.84
            },
            {
                "name":"义务教育社会科教师",
                "value":7.11
            },
            {
                "name":"义务教育理工科教师",
                "value":6.61
            },
            {
                "name":"高中教育（含职业院校）语文教师",
                "value":8.5
            },
            {
                "name":"高中学段（含职校）数学教师",
                "value":8.15
            },
            {
                "name":"高中学段（含职校） 英语教师",
                "value":12.54
            },
            {
                "name":"高中学段（含职校）理工科教师",
                "value":5.99
            },
            {
                "name":"高中学段（含职校）艺体科教师",
                "value":7.23
            },
            {
                "name":"高中学段（含职校）社会科教师",
                "value":8.74
            }
        ],
        "standardSelf":[
            {
                "name":"幼儿园教师",
                "value":4.89
            },
            {
                "name":"义务教育语文教师",
                "value":9.61
            },
            {
                "name":"义务教育数学教师",
                "value":9.03
            },
            {
                "name":"义务教育英语教师",
                "value":6.29
            },
            {
                "name":"义务教育艺体科教师",
                "value":6.79
            },
            {
                "name":"义务教育社会科教师",
                "value":7.12
            },
            {
                "name":"义务教育理工科教师",
                "value":6.61
            },
            {
                "name":"高中教育（含职业院校）语文教师",
                "value":6.83
            },
            {
                "name":"高中学段（含职校）数学教师",
                "value":6.49
            },
            {
                "name":"高中学段（含职校） 英语教师",
                "value":5.87
            },
            {
                "name":"高中学段（含职校）理工科教师",
                "value":7.99
            },
            {
                "name":"高中学段（含职校）艺体科教师",
                "value":6.76
            },
            {
                "name":"高中学段（含职校）社会科教师",
                "value":8.83
            }
        ]
    },
    {
        "type":"综合育人",
        "scoreRateDistribution":[
            "90.94",
            "20.75",
            "15.12",
            "10.40",
            "7.43",
            "10.27",
            "5.71",
            "4.29",
            "2.40",
            "2.23",
            "2.75",
            "4.86",
            "1.44",
            "3.30"
        ],
        "distribution":{
            "distribution0":[
                {
                    "name":"优秀",
                    "value":466,
                    "proportion":99.72
                },
                {
                    "name":"良好",
                    "value":81,
                    "proportion":96.02
                },
                {
                    "name":"及格",
                    "value":905,
                    "proportion":93.43
                },
                {
                    "name":"不及格",
                    "value":1098,
                    "proportion":84.78
                }
            ],
            "distribution1":[
                {
                    "name":"优秀",
                    "value":327,
                    "proportion":99.72
                },
                {
                    "name":"良好",
                    "value":54,
                    "proportion":96.03
                },
                {
                    "name":"及格",
                    "value":122,
                    "proportion":92.6
                },
                {
                    "name":"不及格",
                    "value":45,
                    "proportion":85.04
                }
            ],
            "distribution2":[
                {
                    "name":"优秀",
                    "value":19,
                    "proportion":99.77
                },
                {
                    "name":"良好",
                    "value":2,
                    "proportion":95.56
                },
                {
                    "name":"及格",
                    "value":151,
                    "proportion":93.5
                },
                {
                    "name":"不及格",
                    "value":262,
                    "proportion":85.28
                }
            ],
            "distribution3":[
                {
                    "name":"优秀",
                    "value":20,
                    "proportion":99.83
                },
                {
                    "name":"良好",
                    "value":3,
                    "proportion":96.3
                },
                {
                    "name":"及格",
                    "value":111,
                    "proportion":93.46
                },
                {
                    "name":"不及格",
                    "value":164,
                    "proportion":84.45
                }
            ],
            "distribution4":[
                {
                    "name":"优秀",
                    "value":16,
                    "proportion":99.93
                },
                {
                    "name":"良好",
                    "value":3,
                    "proportion":95.56
                },
                {
                    "name":"及格",
                    "value":76,
                    "proportion":93.65
                },
                {
                    "name":"不及格",
                    "value":115,
                    "proportion":86.42
                }
            ],
            "distribution5":[
                {
                    "name":"优秀",
                    "value":25,
                    "proportion":99.78
                },
                {
                    "name":"良好",
                    "value":3,
                    "proportion":96.3
                },
                {
                    "name":"及格",
                    "value":147,
                    "proportion":93.84
                },
                {
                    "name":"不及格",
                    "value":112,
                    "proportion":85.76
                }
            ],
            "distribution6":[
                {
                    "name":"优秀",
                    "value":20,
                    "proportion":99.56
                },
                {
                    "name":"良好",
                    "value":1,
                    "proportion":96.67
                },
                {
                    "name":"及格",
                    "value":78,
                    "proportion":93.42
                },
                {
                    "name":"不及格",
                    "value":61,
                    "proportion":85.19
                }
            ],
            "distribution7":[
                {
                    "name":"优秀",
                    "value":5,
                    "proportion":99.33
                },
                {
                    "name":"良好",
                    "value":1,
                    "proportion":96.67
                },
                {
                    "name":"及格",
                    "value":42,
                    "proportion":93.73
                },
                {
                    "name":"不及格",
                    "value":75,
                    "proportion":85.35
                }
            ],
            "distribution8":[
                {
                    "name":"优秀",
                    "value":3,
                    "proportion":99.63
                },
                {
                    "name":"良好",
                    "value":6,
                    "proportion":96.11
                },
                {
                    "name":"及格",
                    "value":27,
                    "proportion":93.17
                },
                {
                    "name":"不及格",
                    "value":33,
                    "proportion":82.49
                }
            ],
            "distribution9":[
                {
                    "name":"优秀",
                    "value":4,
                    "proportion":99.72
                },
                {
                    "name":"良好",
                    "value":1,
                    "proportion":95.56
                },
                {
                    "name":"及格",
                    "value":30,
                    "proportion":93.85
                },
                {
                    "name":"不及格",
                    "value":29,
                    "proportion":81.88
                }
            ],
            "distribution10":[
                {
                    "name":"优秀",
                    "value":8,
                    "proportion":99.86
                },
                {
                    "name":"良好",
                    "value":1,
                    "proportion":96.67
                },
                {
                    "name":"及格",
                    "value":28,
                    "proportion":93.49
                },
                {
                    "name":"不及格",
                    "value":41,
                    "proportion":85.15
                }
            ],
            "distribution11":[
                {
                    "name":"优秀",
                    "value":17,
                    "proportion":99.61
                },
                {
                    "name":"良好",
                    "value":5,
                    "proportion":95.56
                },
                {
                    "name":"及格",
                    "value":73,
                    "proportion":93.41
                },
                {
                    "name":"不及格",
                    "value":40,
                    "proportion":85.31
                }
            ],
            "distribution12":[
                {
                    "name":"优秀",
                    "value":2,
                    "proportion":100
                },
                {
                    "name":"良好",
                    "value":1,
                    "proportion":96.67
                },
                {
                    "name":"及格",
                    "value":11,
                    "proportion":92.22
                },
                {
                    "name":"不及格",
                    "value":28,
                    "proportion":84.25
                }
            ],
            "distribution13":[
                {
                    "name":"及格",
                    "value":9,
                    "proportion":93.58
                },
                {
                    "name":"不及格",
                    "value":93,
                    "proportion":81.35
                }
            ]
        },
        "distributionTable":[
            {
                "name":"幼儿园教师",
                "excellent":"59.67(327人)",
                "good":"9.85(54人)",
                "pass":"22.26(122人)",
                "fail":"8.21(45人)"
            },
            {
                "name":"义务教育语文教师",
                "excellent":"4.38(19人)",
                "good":"0.46(2人)",
                "pass":"34.79(151人)",
                "fail":"60.37(262人)"
            },
            {
                "name":"义务教育数学教师",
                "excellent":"6.71(20人)",
                "good":"1.01(3人)",
                "pass":"37.25(111人)",
                "fail":"55.03(164人)"
            },
            {
                "name":"义务教育英语教师",
                "excellent":"7.62(16人)",
                "good":"1.43(3人)",
                "pass":"36.19(76人)",
                "fail":"54.76(115人)"
            },
            {
                "name":"义务教育艺体科教师",
                "excellent":"8.71(25人)",
                "good":"1.05(3人)",
                "pass":"51.22(147人)",
                "fail":"39.02(112人)"
            },
            {
                "name":"义务教育社会科教师",
                "excellent":"12.50(20人)",
                "good":"0.63(1人)",
                "pass":"48.75(78人)",
                "fail":"38.13(61人)"
            },
            {
                "name":"义务教育理工科教师",
                "excellent":"4.07(5人)",
                "good":"0.81(1人)",
                "pass":"34.15(42人)",
                "fail":"60.98(75人)"
            },
            {
                "name":"高中教育（含职业院校）语文教师",
                "excellent":"4.35(3人)",
                "good":"8.70(6人)",
                "pass":"39.13(27人)",
                "fail":"47.83(33人)"
            },
            {
                "name":"高中学段（含职校）数学教师",
                "excellent":"6.25(4人)",
                "good":"1.56(1人)",
                "pass":"46.88(30人)",
                "fail":"45.31(29人)"
            },
            {
                "name":"高中学段（含职校） 英语教师",
                "excellent":"10.26(8人)",
                "good":"1.28(1人)",
                "pass":"35.90(28人)",
                "fail":"52.56(41人)"
            },
            {
                "name":"高中学段（含职校）理工科教师",
                "excellent":"12.59(17人)",
                "good":"3.70(5人)",
                "pass":"54.07(73人)",
                "fail":"29.63(40人)"
            },
            {
                "name":"高中学段（含职校）艺体科教师",
                "excellent":"4.76(2人)",
                "good":"2.38(1人)",
                "pass":"26.19(11人)",
                "fail":"66.67(28人)"
            },
            {
                "name":"高中学段（含职校）社会科教师",
                "excellent":"0(0人)",
                "good":"0(0人)",
                "pass":"8.82(9人)",
                "fail":"91.18(93人)"
            }
        ],
        "average":{
            "attitudeAver":[
                {
                    "name":"幼儿园教师",
                    "value":18
                },
                {
                    "name":"义务教育语文教师",
                    "value":13
                },
                {
                    "name":"义务教育数学教师",
                    "value":9
                },
                {
                    "name":"义务教育英语教师",
                    "value":6
                },
                {
                    "name":"义务教育艺体科教师",
                    "value":9
                },
                {
                    "name":"义务教育社会科教师",
                    "value":5
                },
                {
                    "name":"义务教育理工科教师",
                    "value":3
                },
                {
                    "name":"高中教育（含职业院校）语文教师",
                    "value":2
                },
                {
                    "name":"高中学段（含职校）数学教师",
                    "value":2
                },
                {
                    "name":"高中学段（含职校） 英语教师",
                    "value":2
                },
                {
                    "name":"高中学段（含职校）理工科教师",
                    "value":4
                },
                {
                    "name":"高中学段（含职校）艺体科教师",
                    "value":1
                },
                {
                    "name":"高中学段（含职校）社会科教师",
                    "value":2
                }
            ],
            "attitudeAverScene":[
                {
                    "name":"幼儿园教师",
                    "value":18
                },
                {
                    "name":"义务教育语文教师",
                    "value":13
                },
                {
                    "name":"义务教育数学教师",
                    "value":9
                },
                {
                    "name":"义务教育英语教师",
                    "value":6
                },
                {
                    "name":"义务教育艺体科教师",
                    "value":9
                },
                {
                    "name":"义务教育社会科教师",
                    "value":5
                },
                {
                    "name":"义务教育理工科教师",
                    "value":3
                },
                {
                    "name":"高中教育（含职业院校）语文教师",
                    "value":2
                },
                {
                    "name":"高中学段（含职校）数学教师",
                    "value":2
                },
                {
                    "name":"高中学段（含职校） 英语教师",
                    "value":2
                },
                {
                    "name":"高中学段（含职校）理工科教师",
                    "value":4
                },
                {
                    "name":"高中学段（含职校）艺体科教师",
                    "value":1
                },
                {
                    "name":"高中学段（含职校）社会科教师",
                    "value":2
                }
            ],
            "attitudeAverSelf":[
                {
                    "name":"幼儿园教师",
                    "value":18
                },
                {
                    "name":"义务教育语文教师",
                    "value":13
                },
                {
                    "name":"义务教育数学教师",
                    "value":9
                },
                {
                    "name":"义务教育英语教师",
                    "value":6
                },
                {
                    "name":"义务教育艺体科教师",
                    "value":9
                },
                {
                    "name":"义务教育社会科教师",
                    "value":5
                },
                {
                    "name":"义务教育理工科教师",
                    "value":3
                },
                {
                    "name":"高中教育（含职业院校）语文教师",
                    "value":2
                },
                {
                    "name":"高中学段（含职校）数学教师",
                    "value":2
                },
                {
                    "name":"高中学段（含职校） 英语教师",
                    "value":2
                },
                {
                    "name":"高中学段（含职校）理工科教师",
                    "value":4
                },
                {
                    "name":"高中学段（含职校）艺体科教师",
                    "value":1
                },
                {
                    "name":"高中学段（含职校）社会科教师",
                    "value":2
                }
            ]
        },
        "minMaxAndMidScene":[
            [
                30,
                45,
                30
            ],
            [
                30,
                45,
                30
            ],
            [
                30,
                45,
                30
            ],
            [
                29,
                45,
                30
            ],
            [
                24,
                45,
                30
            ],
            [
                30,
                44,
                30
            ],
            [
                27,
                44,
                30
            ],
            [
                26,
                42,
                30
            ],
            [
                18,
                44,
                30
            ],
            [
                25,
                45,
                30
            ],
            [
                29,
                45,
                30
            ],
            [
                24,
                45,
                30
            ],
            [
                28,
                45,
                30
            ]
        ],
        "minMaxAndMidSelf":[
            [
                30,
                45,
                30
            ],
            [
                30,
                35,
                30
            ],
            [
                30,
                40,
                30
            ],
            [
                30,
                40,
                30
            ],
            [
                30,
                40,
                30
            ],
            [
                26,
                40,
                30
            ],
            [
                29,
                40,
                30
            ],
            [
                28,
                40,
                30
            ],
            [
                30,
                40,
                30
            ],
            [
                30,
                40,
                30
            ],
            [
                30,
                40,
                30
            ],
            [
                24,
                35,
                30
            ],
            [
                30,
                32,
                30
            ]
        ],
        "standardScene":[
            {
                "name":"幼儿园教师",
                "value":7.46
            },
            {
                "name":"义务教育语文教师",
                "value":3.87
            },
            {
                "name":"义务教育数学教师",
                "value":3.45
            },
            {
                "name":"义务教育英语教师",
                "value":5.99
            },
            {
                "name":"义务教育艺体科教师",
                "value":3.95
            },
            {
                "name":"义务教育社会科教师",
                "value":5.3
            },
            {
                "name":"义务教育理工科教师",
                "value":4.89
            },
            {
                "name":"高中教育（含职业院校）语文教师",
                "value":6.64
            },
            {
                "name":"高中学段（含职校）数学教师",
                "value":6.02
            },
            {
                "name":"高中学段（含职校） 英语教师",
                "value":4.38
            },
            {
                "name":"高中学段（含职校）理工科教师",
                "value":3.97
            },
            {
                "name":"高中学段（含职校）艺体科教师",
                "value":4.72
            },
            {
                "name":"高中学段（含职校）社会科教师",
                "value":5.92
            }
        ],
        "standardSelf":[
            {
                "name":"幼儿园教师",
                "value":2.28
            },
            {
                "name":"义务教育语文教师",
                "value":8.2
            },
            {
                "name":"义务教育数学教师",
                "value":5.37
            },
            {
                "name":"义务教育英语教师",
                "value":4.29
            },
            {
                "name":"义务教育艺体科教师",
                "value":3.84
            },
            {
                "name":"义务教育社会科教师",
                "value":5.75
            },
            {
                "name":"义务教育理工科教师",
                "value":4.68
            },
            {
                "name":"高中教育（含职业院校）语文教师",
                "value":5.25
            },
            {
                "name":"高中学段（含职校）数学教师",
                "value":4.63
            },
            {
                "name":"高中学段（含职校） 英语教师",
                "value":5.44
            },
            {
                "name":"高中学段（含职校）理工科教师",
                "value":3.91
            },
            {
                "name":"高中学段（含职校）艺体科教师",
                "value":4.69
            },
            {
                "name":"高中学段（含职校）社会科教师",
                "value":4.98
            }
        ]
    },
    {
        "type":"自主发展",
        "scoreRateDistribution":[
            "88.67",
            "19.79",
            "14.64",
            "9.99",
            "7.42",
            "9.96",
            "5.72",
            "4.25",
            "2.44",
            "2.21",
            "2.69",
            "4.75",
            "1.41",
            "3.38"
        ],
        "distribution":{
            "distribution0":[
                {
                    "name":"优秀",
                    "value":207,
                    "proportion":99.66
                },
                {
                    "name":"良好",
                    "value":27,
                    "proportion":95.88
                },
                {
                    "name":"及格",
                    "value":843,
                    "proportion":93.63
                }
            ],
            "distribution1":[
                {
                    "name":"优秀",
                    "value":75,
                    "proportion":99.72
                },
                {
                    "name":"良好",
                    "value":11,
                    "proportion":95.96
                },
                {
                    "name":"及格",
                    "value":300,
                    "proportion":93.6
                }
            ],
            "distribution2":[
                {
                    "name":"优秀",
                    "value":5,
                    "proportion":100
                },
                {
                    "name":"及格",
                    "value":72,
                    "proportion":93.72
                }
            ],
            "distribution3":[
                {
                    "name":"良好",
                    "value":1,
                    "proportion":95.56
                },
                {
                    "name":"及格",
                    "value":38,
                    "proportion":93.74
                }
            ],
            "distribution4":[
                {
                    "name":"优秀",
                    "value":17,
                    "proportion":99.54
                },
                {
                    "name":"良好",
                    "value":6,
                    "proportion":95.93
                },
                {
                    "name":"及格",
                    "value":93,
                    "proportion":93.38
                }
            ],
            "distribution5":[
                {
                    "name":"优秀",
                    "value":30,
                    "proportion":99.59
                },
                {
                    "name":"良好",
                    "value":1,
                    "proportion":96.67
                },
                {
                    "name":"及格",
                    "value":89,
                    "proportion":93.93
                }
            ],
            "distribution6":[
                {
                    "name":"优秀",
                    "value":29,
                    "proportion":99.54
                },
                {
                    "name":"良好",
                    "value":3,
                    "proportion":95.93
                },
                {
                    "name":"及格",
                    "value":66,
                    "proportion":93.5
                }
            ],
            "distribution7":[
                {
                    "name":"优秀",
                    "value":11,
                    "proportion":99.49
                },
                {
                    "name":"及格",
                    "value":32,
                    "proportion":94.03
                }
            ],
            "distribution8":[
                {
                    "name":"优秀",
                    "value":12,
                    "proportion":99.91
                },
                {
                    "name":"良好",
                    "value":4,
                    "proportion":95.56
                },
                {
                    "name":"及格",
                    "value":21,
                    "proportion":93.28
                }
            ],
            "distribution9":[
                {
                    "name":"优秀",
                    "value":5,
                    "proportion":99.56
                },
                {
                    "name":"及格",
                    "value":27,
                    "proportion":93.42
                }
            ],
            "distribution10":[
                {
                    "name":"优秀",
                    "value":6,
                    "proportion":99.81
                },
                {
                    "name":"良好",
                    "value":1,
                    "proportion":95.56
                },
                {
                    "name":"及格",
                    "value":24,
                    "proportion":93.89
                }
            ],
            "distribution11":[
                {
                    "name":"优秀",
                    "value":16,
                    "proportion":99.58
                },
                {
                    "name":"及格",
                    "value":51,
                    "proportion":93.51
                }
            ],
            "distribution12":[
                {
                    "name":"及格",
                    "value":12,
                    "proportion":93.89
                }
            ],
            "distribution13":[
                {
                    "name":"优秀",
                    "value":1,
                    "proportion":100
                },
                {
                    "name":"及格",
                    "value":18,
                    "proportion":93.7
                }
            ]
        },
        "distributionTable":[
            {
                "name":"幼儿园教师",
                "excellent":"13.69(75人)",
                "good":"2.01(11人)",
                "pass":"54.74(300人)",
                "fail":"0(0人)"
            },
            {
                "name":"义务教育语文教师",
                "excellent":"1.15(5人)",
                "good":"0(0人)",
                "pass":"16.59(72人)",
                "fail":"0(0人)"
            },
            {
                "name":"义务教育数学教师",
                "excellent":"0(0人)",
                "good":"0.34(1人)",
                "pass":"12.75(38人)",
                "fail":"0(0人)"
            },
            {
                "name":"义务教育英语教师",
                "excellent":"8.10(17人)",
                "good":"2.86(6人)",
                "pass":"44.29(93人)",
                "fail":"0(0人)"
            },
            {
                "name":"义务教育艺体科教师",
                "excellent":"10.45(30人)",
                "good":"0.35(1人)",
                "pass":"31.01(89人)",
                "fail":"0(0人)"
            },
            {
                "name":"义务教育社会科教师",
                "excellent":"18.13(29人)",
                "good":"1.88(3人)",
                "pass":"41.25(66人)",
                "fail":"0(0人)"
            },
            {
                "name":"义务教育理工科教师",
                "excellent":"8.94(11人)",
                "good":"0(0人)",
                "pass":"26.02(32人)",
                "fail":"0(0人)"
            },
            {
                "name":"高中教育（含职业院校）语文教师",
                "excellent":"17.39(12人)",
                "good":"5.80(4人)",
                "pass":"30.43(21人)",
                "fail":"0(0人)"
            },
            {
                "name":"高中学段（含职校）数学教师",
                "excellent":"7.81(5人)",
                "good":"0(0人)",
                "pass":"42.19(27人)",
                "fail":"0(0人)"
            },
            {
                "name":"高中学段（含职校） 英语教师",
                "excellent":"7.69(6人)",
                "good":"1.28(1人)",
                "pass":"30.77(24人)",
                "fail":"0(0人)"
            },
            {
                "name":"高中学段（含职校）理工科教师",
                "excellent":"11.85(16人)",
                "good":"0(0人)",
                "pass":"37.78(51人)",
                "fail":"0(0人)"
            },
            {
                "name":"高中学段（含职校）艺体科教师",
                "excellent":"0(0人)",
                "good":"0(0人)",
                "pass":"28.57(12人)",
                "fail":"0(0人)"
            },
            {
                "name":"高中学段（含职校）社会科教师",
                "excellent":"0.98(1人)",
                "good":"0(0人)",
                "pass":"17.65(18人)",
                "fail":"0(0人)"
            }
        ],
        "average":{
            "attitudeAver":[
                {
                    "name":"幼儿园教师",
                    "value":17
                },
                {
                    "name":"义务教育语文教师",
                    "value":13
                },
                {
                    "name":"义务教育数学教师",
                    "value":8
                },
                {
                    "name":"义务教育英语教师",
                    "value":6
                },
                {
                    "name":"义务教育艺体科教师",
                    "value":8
                },
                {
                    "name":"义务教育社会科教师",
                    "value":5
                },
                {
                    "name":"义务教育理工科教师",
                    "value":3
                },
                {
                    "name":"高中教育（含职业院校）语文教师",
                    "value":2
                },
                {
                    "name":"高中学段（含职校）数学教师",
                    "value":1
                },
                {
                    "name":"高中学段（含职校） 英语教师",
                    "value":2
                },
                {
                    "name":"高中学段（含职校）理工科教师",
                    "value":4
                },
                {
                    "name":"高中学段（含职校）艺体科教师",
                    "value":1
                },
                {
                    "name":"高中学段（含职校）社会科教师",
                    "value":3
                }
            ],
            "attitudeAverScene":[
                {
                    "name":"幼儿园教师",
                    "value":17
                },
                {
                    "name":"义务教育语文教师",
                    "value":13
                },
                {
                    "name":"义务教育数学教师",
                    "value":8
                },
                {
                    "name":"义务教育英语教师",
                    "value":6
                },
                {
                    "name":"义务教育艺体科教师",
                    "value":8
                },
                {
                    "name":"义务教育社会科教师",
                    "value":5
                },
                {
                    "name":"义务教育理工科教师",
                    "value":3
                },
                {
                    "name":"高中教育（含职业院校）语文教师",
                    "value":2
                },
                {
                    "name":"高中学段（含职校）数学教师",
                    "value":1
                },
                {
                    "name":"高中学段（含职校） 英语教师",
                    "value":2
                },
                {
                    "name":"高中学段（含职校）理工科教师",
                    "value":4
                },
                {
                    "name":"高中学段（含职校）艺体科教师",
                    "value":1
                },
                {
                    "name":"高中学段（含职校）社会科教师",
                    "value":3
                }
            ],
            "attitudeAverSelf":[
                {
                    "name":"幼儿园教师",
                    "value":17
                },
                {
                    "name":"义务教育语文教师",
                    "value":13
                },
                {
                    "name":"义务教育数学教师",
                    "value":8
                },
                {
                    "name":"义务教育英语教师",
                    "value":6
                },
                {
                    "name":"义务教育艺体科教师",
                    "value":8
                },
                {
                    "name":"义务教育社会科教师",
                    "value":5
                },
                {
                    "name":"义务教育理工科教师",
                    "value":3
                },
                {
                    "name":"高中教育（含职业院校）语文教师",
                    "value":2
                },
                {
                    "name":"高中学段（含职校）数学教师",
                    "value":1
                },
                {
                    "name":"高中学段（含职校） 英语教师",
                    "value":2
                },
                {
                    "name":"高中学段（含职校）理工科教师",
                    "value":4
                },
                {
                    "name":"高中学段（含职校）艺体科教师",
                    "value":1
                },
                {
                    "name":"高中学段（含职校）社会科教师",
                    "value":3
                }
            ]
        },
        "minMaxAndMidScene":[
            [
                25,
                44,
                30
            ],
            [
                30,
                45,
                30
            ],
            [
                30,
                44,
                30
            ],
            [
                30,
                44,
                30
            ],
            [
                24,
                45,
                30
            ],
            [
                28,
                43,
                30
            ],
            [
                27,
                44,
                30
            ],
            [
                24,
                42,
                30
            ],
            [
                29,
                42,
                30
            ],
            [
                29,
                45,
                30
            ],
            [
                30,
                44,
                30
            ],
            [
                30,
                45,
                30
            ],
            [
                23,
                45,
                30
            ]
        ],
        "minMaxAndMidSelf":[
            [
                30,
                40,
                30
            ],
            [
                30,
                35,
                30
            ],
            [
                26,
                35,
                30
            ],
            [
                30,
                40,
                30
            ],
            [
                30,
                40,
                30
            ],
            [
                30,
                40,
                30
            ],
            [
                29,
                40,
                30
            ],
            [
                30,
                40,
                30
            ],
            [
                30,
                40,
                30
            ],
            [
                30,
                40,
                30
            ],
            [
                24,
                40,
                30
            ],
            [
                24,
                35,
                30
            ],
            [
                30,
                35,
                30
            ]
        ],
        "standardScene":[
            {
                "name":"幼儿园教师",
                "value":8
            },
            {
                "name":"义务教育语文教师",
                "value":4.88
            },
            {
                "name":"义务教育数学教师",
                "value":4.76
            },
            {
                "name":"义务教育英语教师",
                "value":7.21
            },
            {
                "name":"义务教育艺体科教师",
                "value":4.47
            },
            {
                "name":"义务教育社会科教师",
                "value":5.83
            },
            {
                "name":"义务教育理工科教师",
                "value":6.91
            },
            {
                "name":"高中教育（含职业院校）语文教师",
                "value":6.58
            },
            {
                "name":"高中学段（含职校）数学教师",
                "value":6.74
            },
            {
                "name":"高中学段（含职校） 英语教师",
                "value":9.68
            },
            {
                "name":"高中学段（含职校）理工科教师",
                "value":4.62
            },
            {
                "name":"高中学段（含职校）艺体科教师",
                "value":5.46
            },
            {
                "name":"高中学段（含职校）社会科教师",
                "value":6.34
            }
        ],
        "standardSelf":[
            {
                "name":"幼儿园教师",
                "value":2.69
            },
            {
                "name":"义务教育语文教师",
                "value":4.11
            },
            {
                "name":"义务教育数学教师",
                "value":3.24
            },
            {
                "name":"义务教育英语教师",
                "value":4.18
            },
            {
                "name":"义务教育艺体科教师",
                "value":5.72
            },
            {
                "name":"义务教育社会科教师",
                "value":3.41
            },
            {
                "name":"义务教育理工科教师",
                "value":4.83
            },
            {
                "name":"高中教育（含职业院校）语文教师",
                "value":6.36
            },
            {
                "name":"高中学段（含职校）数学教师",
                "value":4.41
            },
            {
                "name":"高中学段（含职校） 英语教师",
                "value":4.93
            },
            {
                "name":"高中学段（含职校）理工科教师",
                "value":7.77
            },
            {
                "name":"高中学段（含职校）艺体科教师",
                "value":6.58
            },
            {
                "name":"高中学段（含职校）社会科教师",
                "value":5.05
            }
        ]
    }
]
