export const ResearchTableData = [
  { teachCount: '548', subject: '幼儿园', period: '学前教育' },
  { teachCount: '119', subject: '体育', period: '小学' },
  { teachCount: '10', subject: '信息科技', period: '小学' },
  { teachCount: '2', subject: '劳技', period: '小学' },
  { teachCount: '10', subject: '心理', period: '小学' },
  { teachCount: '171', subject: '数学', period: '小学' },
  { teachCount: '21', subject: '特教', period: '小学' },
  { teachCount: '35', subject: '美术', period: '小学' },
  { teachCount: '28', subject: '自然', period: '小学' },
  { teachCount: '98', subject: '英语', period: '小学' },
  { teachCount: '336', subject: '语文', period: '小学' },
  { teachCount: '9', subject: '道德与法治', period: '小学' },
  { teachCount: '41', subject: '音乐', period: '小学' },



  { teachCount: '56', subject: '体育', period: '初中' },
  { teachCount: '13', subject: '信息科技', period: '初中' },
  { teachCount: '3', subject: '劳技', period: '初中' },
  { teachCount: '14', subject: '化学', period: '初中' },
  { teachCount: '38', subject: '历史', period: '初中' },
  { teachCount: '18', subject: '地理', period: '初中' },
  { teachCount: '10', subject: '心理', period: '初中' },
  { teachCount: '128', subject: '数学', period: '初中' },
  { teachCount: '23', subject: '物理', period: '初中' },
  { teachCount: '19', subject: '生命科学', period: '初中' },
  { teachCount: '12', subject: '科学', period: '初中' },

  { teachCount: '17', subject: '美术', period: '初中' },
  { teachCount: '112', subject: '英语', period: '初中' },
  { teachCount: '101', subject: '语文', period: '初中' },
  { teachCount: '46', subject: '道德与法治', period: '初中' },
  { teachCount: '16', subject: '音乐', period: '初中' },


  { teachCount: '30', subject: '体育', period: '高中' },
  { teachCount: '12', subject: '信息科技', period: '高中' },
  { teachCount: '38', subject: '化学', period: '高中' },
  { teachCount: '34', subject: '历史', period: '高中' },
  { teachCount: '21', subject: '地理', period: '高中' },
  { teachCount: '7', subject: '心理', period: '高中' },
  { teachCount: '59', subject: '数学', period: '高中' },
  { teachCount: '32', subject: '物理', period: '高中' },
  { teachCount: '23', subject: '生命科学', period: '高中' },
  { teachCount: '3', subject: '美术', period: '高中' },
  { teachCount: '67', subject: '英语', period: '高中' },
  { teachCount: '59', subject: '语文', period: '高中' },
  { teachCount: '31', subject: '道德与法治', period: '高中' },
  { teachCount: '4', subject: '音乐', period: '高中' },

  { teachCount: '1', subject: '人工智能', period: '职校' },
  { teachCount: '4', subject: '体育', period: '职校' },
  { teachCount: '3', subject: '信息科技', period: '职校' },
  { teachCount: '4', subject: '历史', period: '职校' },
  { teachCount: '3', subject: '心理', period: '职校' },
  { teachCount: '1', subject: '数学', period: '职校' },
  { teachCount: '20', subject: '职教专业课', period: '职校' },
  { teachCount: '11', subject: '英语', period: '职校' },
  { teachCount: '8', subject: '语文', period: '职校' },
  { teachCount: '1', subject: '跨境电子商务', period: '职校' },
  { teachCount: '3', subject: '道德与法治', period: '职校' },
  { teachCount: '1', subject: '音乐', period: '职校' },
  { teachCount: '2', subject: '飞行器维修技术', period: '职校' },
  { teachCount: '1', subject: '市场营销', period: '高校' },
  { teachCount: '1', subject: '数学', period: '高校' },
  { teachCount: '3', subject: '计算机科学与技术', period: '高校' },

  { teachCount: '1', subject: '教育与心理', period: '其他' },
  { teachCount: '3', subject: '语文', period: '其他' },



]
export const ContentTableData = [
  { id: 0, first: '1.职业态度', second: '1.1师德师风', third: '具有理想信念，学习贯彻习近平新时代中国特色社会主义思想，树立职业理想，立志成为四有好老师' },
  { id: 0, first: '1.职业态度', second: '1.1师德师风', third: '遵守师德规范，坚定政治方向，积极践行社会主义核心价值观，深入贯彻党的教育方针，以立德树人为己任' },
  { id: 0, first: '1.职业态度', second: '1.2教育理念', third: '格守师德准则。依法执教意识，遵守中小学教师职业道德规范，职业理想、强烈的职业认同感和勇于奉献的敬业精神' },
  { id: 0, first: '1.职业态度', second: '1.2教育理念', third: '具有教书育人意识，理解拟任教学科课程独特的育人功能' },
  { id: 0, first: '1.职业态度', second: '1.2教育理念', third: '理解教育对学生发展的价值和意义，认同促进学生全面而有个性地发展的理念 ' },
  { id: 0, first: '1.职业态度', second: '1.2师德师风', third: '关爱学生，促进学生身心健康发展，乐于为学生创造发展的条件和机会' },
  { id: 1, first: '2.教学实践', second: '2.1学科知识', third: '掌握、理解所教学科的基本知识、基本原理和基本技能，具有一定的综合运用学科知识的能力' },
  { id: 1, first: '2.教学实践', second: '2.1学科知识', third: '了解拟任教学科与其他学科的联系，了解学习判学相关知识' },
  { id: 1, first: '2.教学实践', second: '2.1学科知识', third: '掌提学科教学知识与策略，能够结合社会生活实践，有效开展学科教学活动' },
  { id: 1, first: '2.教学实践', second: '2.2教学设计', third: '基于新课标进行教学设计，熟悉拟任教学科的课程标准和教材，理解教材的编写逻辑和体系结构' },
  { id: 1, first: '2.教学实践', second: '2.2教学设计', third: '能根据课程标准要求和学情分析确定怡当的学习目标和学习重点，设计学习活动，形成教案与学案' },
  { id: 1, first: '2.教学实践', second: '2.2教学设计', third: '能根据教学要求和学生兴趣进行教学设计' },
  { id: 1, first: '2.教学实践', second: '2.3课程教学', third: '建立学习内容与生活经验之间的联系能够创设教学情境' },
  { id: 1, first: '2.教学实践', second: '2.3课程教学', third: '基本掌提教学组织与课堂管理的形式和策略，能够科学准确地呈现和表达教学内容' },
  { id: 1, first: '2.教学实践', second: '2.3课程教学', third: '能够根据学生课堂反应及时调整教学活动，控制教学时间和教学节奏，合理设置提问与讨论' },
  { id: 1, first: '2.教学实践', second: '2.4信息素养(数字素养)', third: '了解信息时代对人才培养的新要求，掌握信息化新技术的常用操作，了解其对教育教学的支持作用。' },
  { id: 1, first: '2.教学实践', second: '2.4信息素养(数字素养)', third: '具有安全、合法与负责任地使用信息与技术，主动适应信息化人工智能等新技术变革积极有效开展教育教学的意识' },
  { id: 1, first: '2.教学实践', second: '2.4信息素养(数字素养)', third: '合理选择与整合信息技术资源，为学生提供丰富的学习机会和个性化学习体验' },
  { id: 2, first: '3.综合育人', second: '3.1学生评价', third: '树立促进学生学习的评价理念' },
  { id: 2, first: '3.综合育人', second: '3.1学生评价', third: '理解教育评价原理，掌握学生评价的方法与技术' },
  { id: 2, first: '3.综合育人', second: '3.1学生评价', third: '能够在教育活动中实施过程评价，初步运用增值评价，合理选取和运用评价工具' },
  { id: 2, first: '3.综合育人', second: '3.2学生指导', third: '树立育人为本、德盲为先理念，盲德意识，树立德育为先理念' },
  { id: 2, first: '3.综合育人', second: '3.2学生指导', third: '基本掌握学生发展指导的方法，能够利用技术手段收集学生成长过程的关键信息，建立学生成长电子档案' },
  { id: 2, first: '3.综合育人', second: '3.2学生指导', third: '有班级建设与管理的能力，能够初步运用信息技术辅助开展班级学生指导活动' },
  { id: 2, first: '3.综合育人', second: '3.3师生沟通', third: '具有沟通技能，具有阅读理解能力、语言与文字表达能力、交流沟通能力、信息获取和处理能力' },
  { id: 2, first: '3.综合育人', second: '3.3师生沟通', third: '掌握基本沟通合作技能与方法，能够在教育实践与学生进行有效沟通交流' },
  { id: 2, first: '3.综合育人', second: '3.3师生沟通', third: '理解师生学习共同体的作用，掌握团队协作的基本策略' },
  { id: 3, first: '4.自主发展', second: '4.1教学反思', third: '且有反思章识和批判性思维素茶' },
  { id: 3, first: '4.自主发展', second: '4.1教学反思', third: '初步掌握教育教学反思的基本方法和策略' },
  { id: 3, first: '4.自主发展', second: '4.1教学反思', third: '能够对教育教学实践活动进行有效的自我诊断，提出改进思路' },
  { id: 3, first: '4.自主发展', second: '4.2教学反思', third: '初步掌握学科研究与教育科学研究的基本方法，能用以分析、研究教育教学实践问题' },
  { id: 3, first: '4.自主发展', second: '4.2教学反思', third: '能够尝试提出解决问题的思路与方法，具有撰写教育教学研究论文的基本能力' },
  { id: 3, first: '4.自主发展', second: '4.2教学反思', third: '掌握专业发展所需的信息技术手段和方法，能在信息技术环境下开展自主学习' },
  { id: 3, first: '4.自主发展', second: '4.3职业规划', third: '了解教师专业发展的要求，具有终身学习与自主发展的意识' },
  { id: 3, first: '4.自主发展', second: '4.3职业规划', third: '能够根据自己的实际情况和职业愿景，制定学习和专业发展规划' },
  { id: 3, first: '4.自主发展', second: '4.3职业规划', third: '具有一定的创新意识和专业反思能力，能够运用批判性思维方法，分析、诊断和改进教育教学问题' }
]


export const ContentTableData2 = [
  { id: 0, first: '1.职业态度', second: '1.1师德师风', third: '具有理想信念，学习贯彻习近平新时代中国特色社会主义思想，树立职业理想，立志成为四有好老师' },
  { id: 0, first: '1.职业态度', second: '1.1师德师风', third: '遵守师德规范，坚定政治方向，积极践行社会主义核心价值观，深入贯彻党的教育方针，以立德树人为己任' },
  { id: 0, first: '1.职业态度', second: '1.2教育理念', third: '格守师德准则。依法执教意识，遵守中小学教师职业道德规范，职业理想、强烈的职业认同感和勇于奉献的敬业精神' },
  { id: 0, first: '1.职业态度', second: '1.2教育理念', third: '具有教书育人意识，理解拟任教学科课程独特的育人功能' },
  { id: 0, first: '1.职业态度', second: '1.2教育理念', third: '理解教育对学生发展的价值和意义，认同促进学生全面而有个性地发展的理念 ' },
  { id: 0, first: '1.职业态度', second: '1.2师德师风', third: '关爱学生，促进学生身心健康发展，乐于为学生创造发展的条件和机会' },
  { id: 1, first: '2.保教知识与能力', second: '2.1幼儿发展知识', third: '了解关于幼儿生存、发展和保护的有关法律法规及政策规定' },
  { id: 1, first: '2.保教知识与能力', second: '2.1幼儿发展知识', third: '掌握不同年龄阶段幼儿身心发展特点、规律以及促进幼儿全面发展的教育策略与方法' },
  { id: 1, first: '2.保教知识与能力', second: '2.1幼儿发展知识', third: '了解幼儿发展中容易出现的问题及具有特殊需要幼儿的身心发展特点及对应教育策略' },

  { id: 1, first: '2.保教知识与能力', second: '2.2幼儿保育和教育知识', third: '掌握幼儿园五大领域教育的学科特点与基本知识' },
  { id: 1, first: '2.保教知识与能力', second: '2.2幼儿保育和教育知识', third: '掌握幼儿园环境创设与利用的知识与方法，能够创设有助于促进幼儿学习与发展的教育环境' },
  { id: 1, first: '2.保教知识与能力', second: '2.2幼儿保育和教育知识', third: '合理安排和组织幼儿园一日生活各个环节，能够将教育灵活地渗透到一日生活中' },
  { id: 1, first: '2.保教知识与能力', second: '2.2幼儿保育和教育知识', third: '重视游戏对幼儿发展的独特作用，能够进行幼儿园游戏活动的支持与引导' },

  
  { id: 1, first: '2.保教知识与能力', second: '2.3课程教学', third: '能够为班级制定阶段性的教育活动计划和具体活动方案' },
  { id: 1, first: '2.保教知识与能力', second: '2.3课程教学', third: '能够有效实施保教活动，并根据幼儿的具体表现和需要，灵活调整活动方案，给予幼儿适宜的指导' },
  { id: 1, first: '2.保教知识与能力', second: '2.3课程教学', third: '能够对保教实践活动进行有效的自我诊断，提出优化改进思路' },
  
  { id: 1, first: '2.保教知识与能力', second: '2.4幼儿观察与教育评价能力', third: '掌握幼儿观察的基本知识，具备观察幼儿、与幼儿互动的能力' },
  { id: 1, first: '2.保教知识与能力', second: '2.4幼儿观察与教育评价能力', third: '能够在保教活动实施前、实施中与实施后，综合运用多种方法，对幼儿园活动进行有效的评价' },
 
  { id: 2, first: '3.综合育人', second: '3.1班级管理', third: '掌握班级组织与管理工作的方法和要点，能结合班级工作实际主动研究班级工作的规律' },
  { id: 2, first: '3.综合育人', second: '3.1班级管理', third: '能够根据幼儿园班级特点，形成良好的班级秩序与规则' },
  { id: 2, first: '3.综合育人', second: '3.1班级管理', third: '科学开发和有效利用各类教育资源，营造民主平等、尊重对话和积极向上的班级心理氛围' },
  { id: 2, first: '3.综合育人', second: '3.2环境育人', third: '重视物质环境的创设，合理规划室内区角与户外空间，为幼儿提供适宜而丰富的玩教具材料及图画书资源等' },
  { id: 2, first: '3.综合育人', second: '3.2环境育人', third: '积极营造安全舒适、自由开放的心理环境，充分发挥环境对于幼儿发展的支持作用，形成良好的园所氛围' },
  { id: 2, first: '3.综合育人', second: '3.3师幼互动', third: '支持幼儿自主选择游戏材料、同伴和玩法，支持幼儿参与一日生活中与自己有关的决策' },
  { id: 2, first: '3.综合育人', second: '3.3师幼互动', third: '重视幼儿通过绘画、讲述等方式对自己经历过的游戏、阅读图画书、观察等活动进行表达表征，教师能一对一倾听并真实记录幼儿的想法和体验' },
  
  { id: 2, first: '3.综合育人', second: '3.4家园社共育', third: '幼儿园与家长建立平等互信关系，通过家长会、家长开放日等多种途径，向家长宣传科学育儿理念和知识' },
  { id: 2, first: '3.综合育人', second: '3.4家园社共育', third: '幼儿园与社区密切合作，积极构建协同育人机制，充分利用自然、社会和文化资源，共同创设良好的育人环境' },
  
  
  
  { id: 3, first: '4.自主发展', second: '4.1教学反思', third: '且有反思章识和批判性思维素茶' },
  { id: 3, first: '4.自主发展', second: '4.1教学反思', third: '初步掌握教育教学反思的基本方法和策略' },
  { id: 3, first: '4.自主发展', second: '4.1教学反思', third: '能够对教育教学实践活动进行有效的自我诊断，提出改进思路' },
  { id: 3, first: '4.自主发展', second: '4.2教学反思', third: '初步掌握学科研究与教育科学研究的基本方法，能用以分析、研究教育教学实践问题' },
  { id: 3, first: '4.自主发展', second: '4.2教学反思', third: '能够尝试提出解决问题的思路与方法，具有撰写教育教学研究论文的基本能力' },
  { id: 3, first: '4.自主发展', second: '4.2教学反思', third: '掌握专业发展所需的信息技术手段和方法，能在信息技术环境下开展自主学习' },
  { id: 3, first: '4.自主发展', second: '4.3职业规划', third: '了解教师专业发展的要求，具有终身学习与自主发展的意识' },
  { id: 3, first: '4.自主发展', second: '4.3职业规划', third: '能够根据自己的实际情况和职业愿景，制定学习和专业发展规划' },
  { id: 3, first: '4.自主发展', second: '4.3职业规划', third: '具有一定的创新意识和专业反思能力，能够运用批判性思维方法，分析、诊断和改进教育教学问题' }
]
